### ISSUE TITLE
Issue with multiple "each" blocks and less/no-duplicate-variables

### ISSUE THREAD

**Issue by AoDev** [stylelint-less/stylelint-less#34]
**Error**

```
unexpected duplicate property in "each" (less/no-duplicate-variables)Stylelint(less/no-duplicate-variables)
```

**Config**

- "stylelint-config-recommended-less": "2.0.0",
- "stylelint-prettier": "4.0.2",
- "stylelint": "15.11.0",

```
{
  "customSyntax": "postcss-less",
  "extends": ["stylelint-config-recommended-less"],
  "ignoreFiles": ["**/*.js", "**/*.jsx"],
  "rules": {
    "selector-class-pattern": null,
    "no-descending-specificity": [true, {"severity": "warning"}]
  }
}
```

**What's happening**

The linter flags an error where it shouldn't.

**Example code**

```less
@spacer-directions: top, right, bottom, left;
@spacer-values: 1, 2, 3, 4;

// .margin-top-1, margin-right-2, ...
each(@spacer-values, .(@svalue) {
  each(@spacer-directions, .(@direction) {
    .margin-@{direction}-@{svalue} {
      margin-@{direction}: @base-gap * @svalue;
    }
  })
});

// .padding-top-1, padding-right-2, ...
each(@spacer-values, .(@svalue) {  // <----- Errored here
  each(@spacer-directions, .(@direction) {
    .padding-@{direction}-@{svalue} {
      padding-@{direction}: @base-gap * @svalue;
    }
  })
});
```

**Observations**

- It is valid less and compiles properly.
- If there is only one "each" block, any of the 2 above, in the current less file, the error disappears.
- Duplicating variables with different name does not resolve the error.
